### ISSUE TITLE
Feature Request: set current sciences & skip technologies that require science not being made.

### ISSUE THREAD

**Issue by presentday-presenttime** [raiguard/UltimateResearchQueue#14]
Often, I will unlock a science pack before I am ready to automate it, suppose blue science. If I have a technology in the queue that requires blue science, but items _later_ in the queue that do not, being able to automatically skip the one with blue science would be a nice feature.

**Comment by raiguard** [comment]
I would rather implement proper queue reordering so you could do this yourself. See #3.
