### ISSUE TITLE
Update to 2.0

### ISSUE THREAD

**Issue by Atria1234** [raiguard/UltimateResearchQueue#25]
### Description

Do you plan to update this mod to 2.0?

### Reproduction

1. Check mod portal
2. Search for "Ultimate research queue"

**Comment by Atria1234** [comment]
Sorry, didn't read the message in mod page

**Comment by brendanmeyer** [comment]
@Atria1234 I've created a fork - it is a bit different and has not been tested, but seems to be working, see: https://mods.factorio.com/mod/UltimateResearchQueue2

**Comment by Atria1234** [comment]
Thank you, but I probably will also stay with vanilla. Only benefit ultimate research queue now has is longer queue and I can live with with shorter one.
