### ISSUE TITLE
Ultimate research queue 2.0 update

### ISSUE THREAD

**Issue by Valoneu** [raiguard/UltimateResearchQueue#26]
Im asking if that mod is ever getting updated cause im missing the automatic requing abiility for infinite science in the game, or maybe it could be added to vanilla :P

**Comment by raiguard** [comment]
I do not plan on updating the mod because I no longer use it. Someone is free to fork it if they so desire. Like you, the only thing I really miss is auto-requeuing, so maybe I can get it into vanilla someday.

**Comment by brendanmeyer** [comment]
@Valoneu I've created a fork - it is a bit different and has not been tested, but seems to be working, see: https://mods.factorio.com/mod/UltimateResearchQueue2
