### ISSUE TITLE
Feature Request / Enhancement / Mod Compatability: Research cost not properly updated when used with Exotic Industries

### ISSUE THREAD

**Issue by Spirevipp** [raiguard/UltimateResearchQueue#4]
Hi, first off i just want to say that i love this and all your other mods, they are just so great!

Last weekend the Exotic Industries mod got released, and it has a scaling research cost: each new tech researched increases the cost of the next.

This increasing research cost does not get properly updated in tooltips, but they do work in the UI when a tech is selected. It does update to the correct value after a game restart. 

Example image:
![ui-bug](https://user-images.githubusercontent.com/20364170/225082867-1a2f625c-0d1c-4227-a37c-46000cda72e8.png)

Link to modpack from the moddev of Exotic Industries containing the recommended mods to use with it:
[Exotic Industries: Official Modpack](https://mods.factorio.com/mod/exotic-industries-modpack)

**Comment by raiguard** [comment]
Ironically, I ran into this myself on my own EI playthrough! I will get to it soon.
