### ISSUE TITLE
Enhancement, single player pause toggle

### ISSUE THREAD

**Issue by Layarion** [raiguard/UltimateResearchQueue#5]
Sometimes when i'm looking through the tree, i want it to remain unpaused. However, i'm playing deathworld currently, and i def want it paused while i waste time thinking about my next move.

Currently I just save the game, do my thinkings, and load it when i'm done messing around with ideas.

**Comment by raiguard** [comment]
Unfortunately, this has one major issue: if the tick is paused, then the GUI does not update correctly. URQ waits until the next tick to update the interface after you click something or a research finishes, to avoid doing more processing than is needed and to greatly simplify the logic. There is no `on_tick_played` event, so the GUI breaks if the tick is paused.
