### ISSUE TITLE
Angelbobs with Technologies enabled

### ISSUE THREAD

**Issue by Schrottobotto** [raiguard/UltimateResearchQueue#8]
### Description

For some reason I can't pick up simple logistics (gray underground belt and splitter). It stages the needed technology Basic technology. It works without the mod.
I use angels industries mod with technology overhaul enabled..

**Comment by HellWatcher** [comment]
Same issue with the same tech. bobslogistics https://pastebin.com/SSViF1bT I turn your mod off to research it and then re-enable it after.
Quite a few mods.
modlist: https://pastebin.com/dLwv8X5Z
